### ISSUE TITLE
UWP Design in Developer Console

### ISSUE THREAD

**Issue by Gargantuan5k** [Guerra24/Firefox-UWP-Style#35]
Hey, this is a feature request: A UWP-style developer console [F12], if possible, would be a really great addition to this theme!
Btw really great work with this project :)

**Comment by Guerra24** [comment]
Hello! Originally the style was enable in the dev console and it even had some tweaks but due to the way element's styles are overridden it would cause issues all over the place to the point it was *not fun* to use.

Although I would like to have a themed dev console it is too complex and it would have to be tested in all supported versions to ensure no breakage and I don't see that being worth specially with my already very limited time.

If you have any specific tweaks or changes I could tackle those.

**Comment by Gargantuan5k** [comment]
That's alright, just a small suggestion, the vanilla dev console looks quite good :) I did have a suspicion that there would be problems with adding styles to it. Closing this, thanks for responding!
