### ISSUE TITLE
Problems with privacy.resistFingerprinting.letterboxing

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#39]
Hey, I have a problem with your css.

I'm using librewolf and when I set privacy.resistFingerprinting.letterboxing to true the browser creates a fix resolution. This resolution works just fine when the browser is not themed, but when it's themed the resolution changes. I don't know why and don't know if this *really* affects my privacy. I made two new profiles to show that the problem isn't extra-config. The only settings I changed were the css settings for the theme works and the privacy.resistFingerprinting.letterboxing.

OS: Windows 10
Browser Version: 94.0.2-3
CSS Version: 89-95 (not the Nightly)

Images:
Not themed: https://vcr.pt/lYo2o
Themed: https://vcr.pt/Nu9CI

**Comment by Guerra24** [comment]
Hello!

I have never used librewolf or resistFingerprinting but the theme navbar is 32px tall in compact and normal density meanwhile the default size is 84px. This increases the available space when using letterboxing.

I tested it with nightly and it works just like default Firefox, you can see that when I increase the size of the default Firefox it jumps at the same place as the themed one.

https://user-images.githubusercontent.com/9023392/144474740-95a5beb0-a92e-49a6-879e-a9ea4b60b01d.mp4

This could cause *privacy* issues with displays that land just in that threshold like in your case. I'm gonna change it so that the workspace area is the same as default Firefox when letterboxin is enabled but meanwhile I will suggest you disabling the theme.

**Comment by Guerra24** [comment]
Made some change so that when letterboxing is enabled it adds some margin to make it the same size as default Firefox. It works with any density setting or bookmarks bar visible/hidden, just make sure to restart Firefox after enabling letterboxing.
The menubar option is unfortunately not supported and that will have a mismatched size.

If this is *good enough* feel free to close the issue, well there is nothing more I can do about it unfortunately.

**Comment by ghost** [comment]
Sorry for the 2 days, I'm busy and only took a look at my email today. Thanks for the change, I understand the limitations and appreciate the help. Have a nice day!
