### ISSUE TITLE
Blur not working in Firefox with Firefox-UWP-Style installed

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#43]
**Firefox version: 96.0.2 Stable Release
Platform: Windows 10 64-bit**

I followed the instructions and was able to enable the newer 'Sun Valley' refresh. But the blur is not working for me.
I've set `layout.css.backdrop-filter.enabled` pref to true.

**Comment by Guerra24** [comment]
Due to [1741779](https://bugzilla.mozilla.org/show_bug.cgi?id=1741779), [1749625](https://bugzilla.mozilla.org/show_bug.cgi?id=1749625) and 4e82c3aac5e9121aecc24d20c5e0efec1959596a backdrop-filter a.k.a background blur has been disabled since Firefox 96, this is not noted in the Readme since it is supposed to be a temporary changed and it will be re-enabled once work on it completes.

**Comment by ghost** [comment]
Oh, thanks for the info. Closing this for now :)
