### ISSUE TITLE
Minimise, Maximise, and Close aren't Aligned on Touch Density

### ISSUE THREAD

**Issue by lzlrd** [Guerra24/Firefox-UWP-Style#50]
There's not much else to say, but here's an image:

![image](https://user-images.githubusercontent.com/24303423/158020478-69eeecb0-ecd0-48d2-a5c3-c558176202e0.png)

I know that some themes aren't meant to be used with higher densities, but even the "Normal" density has a gap...

![image](https://user-images.githubusercontent.com/24303423/158020513-3230d829-be46-47dc-a8d8-27e5dcdab418.png)

...and the "Normal" density is much more compact than Edge...

![image](https://user-images.githubusercontent.com/24303423/158020562-83653fc9-8d0a-4959-830c-e499af0459f4.png)

...and other Fluent Design (especially Sun Valley/WinUI 3) applications.

**Comment by Guerra24** [comment]
Actually... that's the standard behavior for UWP apps.
![image](https://user-images.githubusercontent.com/9023392/158029116-791d1fde-7730-4bed-8957-1a536226eb49.png)
I think you are using non-integer scaling which is probably the reason why it doesn't fit correctly.
![explorer_2022-03-12_11-59-45](https://user-images.githubusercontent.com/9023392/158029378-66ae66e9-7be8-4eb9-8883-78bab726fcd6.gif)

Because it is not an Edge theme it does not tries to mimic it, the tab bar/nav bar size is personal preference.

If you want to change the tab bar/nav bar size add the following into `customChrome.css`

```css
	--tab-min-height: 42px !important;
	--uwp-urlbar-height: 42px !important;
	--uwp-navbar-letterbox: 0px !important;
	--uwp-navbar-letterbox-bookmarks: 0px !important;
```
Adjust to preference. It also disables the letterboxing margin.

**Comment by lazerl0rd** [comment]
> Actually... that's the standard behavior for UWP apps.

I assumed that was an inconsistency on Microsoft's side, since for other apps with a "bar" at the top [which is darker than the "main" app interface] the navigation? buttons are stretched to match it (eg. Edge).

> I think you are using non-integer scaling which is probably the reason why it doesn't fit correctly.

**Comment by lzlrd** [comment]
> Actually... that's the standard behavior for UWP apps.

I assumed that was an inconsistency on Microsoft's side, since some other apps with a "bar" at the top [which is darker than the "main" app interface] the navigation? buttons are stretched to match it.

> I think you are using non-integer scaling which is probably the reason why it doesn't fit correctly.

I am, yes, though I'm not sure what you're referring to by "it doesn't fit" here since your GIF exhibits the same "problems" I brought up.

> Because it is not an Edge theme it does not tries to mimic it, the tab bar/nav bar size is personal preference.

Alright, if that's the reasoning then I'm content with it as is.

> If you want to change the tab bar/nav bar size add the following into customChrome.css

Thanks for the tip! It seems...
> ```css
> --tab-min-height: 42px !important;
> --uwp-urlbar-height: 42px !important;
> ```
...isn't making any difference for me, however.

**Comment by Guerra24** [comment]
> I assumed that was an inconsistency on Microsoft's side, since some other apps with a "bar" at the top [which is darker than the "main" app interface] the navigation? buttons are stretched to match it.

This is quite common. UWP apps have a predefined and enforced titlebar and buttons but Win32 apps can go wild so for the sake of consistency and because the theme tries to mimic UWP the titlebar and buttons were made to respect the default behavior.

> I am, yes, though I'm not sure what you're referring to by "it doesn't fit" here since your GIF exhibits the same "problems" I brought up.

Fit as in not leaving a gap in compact/normal mode. This is a bug when scaling but I'm not sure how to fix it properly, I'll check.
Touch mode is gonna have the gap regardless of scaling setting.

> ...isn't making any difference for me, however.

It might be in touch mode. Add another selector like this:

```css
:root[uidensity="touch"] {
	--tab-min-height: 50px !important;
	--uwp-urlbar-height: 50px !important;
}
```

![image](https://user-images.githubusercontent.com/9023392/159556329-14d6af2c-7b60-44a7-9cb9-535df3175d1e.png)

**Comment by lzlrd** [comment]
> It might be in touch mode. Add another selector like this:
> 
> ```css
> :root[uidensity="touch"] {
> 	--tab-min-height: 50px !important;
> 	--uwp-urlbar-height: 50px !important;
> }
> ```

That works, thanks.
