### ISSUE TITLE
Autoscroll Cursor Bug

### ISSUE THREAD

**Issue by dr-baba** [Guerra24/Firefox-UWP-Style#56]
Hi again, the autoscroll cursor when you middle click is just a blob. Not sure if this is intentional or a bug.

Theme
![image](https://user-images.githubusercontent.com/50979846/167349600-9e4193fd-789a-4786-ba24-872a9c8faacc.png)

Regular Firefox
![image](https://user-images.githubusercontent.com/50979846/167349613-1e798629-57c6-4418-a9e1-3c119fb26164.png)

**Comment by Guerra24** [comment]
This is an unfixable bug, it's a side effect of styling all context menus. Well it could be fixed with JS css injection but I don't want to add it unless there is an automated out-of-the-box way to do load it that does not involve extra setup steps.

I personally don't mind it and works just fine as it is so at least from me I'm not gonna try to fix it anytime soon.

**Comment by dr-baba** [comment]
A small price to pay. Closed.

**Comment by ghost** [comment]
> a side effect of styling all context menus

Can styling all context menus be avoided?



> works just fine as it is

Hmm, not so much. I reported this because I'm having accessibility issues, and I've rolled back to when it used to work.

**Comment by Guerra24** [comment]
> Can styling all context menus be avoided?

Not really, I mean *that's the point* of the theme.

> I reported this because I'm having accessibility issues

Would you mind giving an example? I'm guessing it is visual related.

You could replace `background` with `background-color` [here](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/base.css#L324) and it should bring back the icon but I'm not sure how well it would hold up. Also dark mode would still be broken.

As I said this *can* be fixed but:
1. I don't really have time to work on it.
2. JS css injection is not out-of-the-box which is a *must* for me, it should work as-is without changing anything.

**Comment by ghost** [comment]
> Not really, I mean _that's the point_ of the theme.

I mean, it worked in previous versions.

> > I reported this because I'm having accessibility issues
> 
> Would you mind giving an example? I'm guessing it is visual related.

Sure :) Because the icon isn't easily visible, I found myself having to search for it to get a reference for my scroll speed (or, direction... I mostly found it a problem when scrolling fast to a point, then slowing down... I'd slow and then change directions by acccident).


> You could replace `background` with `background-color` [here](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/base.css#L324) and it should bring back the icon but I'm not sure how well it would hold up. Also dark mode would still be broken.

I'm using dark mode exclusively and never saw a problem with it...


> As I said this _can_ be fixed but:
> 
>     1. I don't really have time to work on it.
> 
>     2. JS css injection is not out-of-the-box which is a _must_ for me, it should work as-is without changing anything.

Yeh, I agree that the JS stuff is a bit too deep. My time is a little short right now too, so I do understand. 

Thinking of the fastest solution, to be honest, I'm of the opinion that the changes should be rolled back, because they caused a lot of regressions; a bunch of minor stuff like the update button in the 'Help... About' window, tickbox in about:addons, etc, which are minor so I didn't bother reporting them; as well as some more major stuff (like breaking compatibility with LWT themes, which is kinda really bad); and fixed nothing (that I've noticed anyway) for me. That's just one user's perspective, though, and I'm sure it's not the whole story, but that's the reality of my experience.

Edit: As discussed in #57 this turns out to date all the way back to the sun valley change, so I can only guess we're too deep to roll back now. It's a shame I didn't try it earlier or I'd have been able to report all the regressions in time, but alas....

Anyway, I don't like to be the bearer of bad news, and I'm happy with the rolled-back version for the time being. But I hope you'll consider this again if you have some time to check it out.

**Comment by zapSNH** [comment]
I think I have a solution to this issue:
(cleaner and more accurate version)
```css
.autoscroller {
	padding: 15px !important;
}
.autoscroller::after {
	display: block;
	content: "";
	width: 30px;
	height: 30px;
	border-radius: 50%;
	background: no-repeat center var(--autoscroll-background-image) rgba(249,249,250,.8);
	border: solid rgba(0,0,0,.4) 1.5px;
	translate: -12px -34px;
	box-shadow: 0 0 4px rgba(0,0,0,.2);
}
```
![image](https://github.com/Guerra24/Firefox-UWP-Style/assets/134786889/3d0baa66-9adb-4302-a34b-4adef3154465)
