### ISSUE TITLE
Recent changes break compatibility with Dark Reader addon / LWT themes

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#57]
Dark Reader employs a theme to provide colour changes to browser chrome, and until recently, that's worked very well. UWP styled elements (like non-rounded corners) remain, however the recent changes seem to hardcode the colours of some elements, which misbehaves a bit and creates inconsistency.

Examples: (note that I use gruvbox colours, so an off-white text and grey background, but some buttons and menu items are white text/icons)

![image](https://user-images.githubusercontent.com/58130821/167913539-b71bb2fd-a68f-4de7-90f6-334f2e767e11.png)

![image](https://user-images.githubusercontent.com/58130821/167913635-1fb3af3e-5037-4c75-9694-32fd73c8954e.png)

**Comment by Guerra24** [comment]
Alright so to begin with custom/lwt themes have never been supported, dark reader has never been tested and/or supported.

The theme got overhauled a while back (6 months ago) with support for multiple styles and I'm guessing that is the reason why it broke now. Aside from tweaks to the variables support for changing anything else is broken due to the workarounds used in some places.

AFAIK nothing has changed with the way colors are set in context menus so I don't know what could be the cause.

**Comment by ghost** [comment]
Looking at it, that seems about right - the file that still works is dated 13/06/2021.

I guess we can file this as "another thing Win11 broke"/"more reasons why rounded corners are a fad that will die again" ;) 
....and I'll just have to use the old version :(

Thanks for a great theme man I have really enjoyed it!
