### ISSUE TITLE
how can i have acrylic on this menus?

### ISSUE THREAD

**Issue by e-splat** [Guerra24/Firefox-UWP-Style#73]
![immagine](https://user-images.githubusercontent.com/82027617/206702267-007a52da-b3a5-4443-9f17-1eb46142a56e.png)
![immagine](https://user-images.githubusercontent.com/82027617/206702272-5afa69f4-f505-4376-b77d-6e5ebc7ff6b1.png)

**Comment by Guerra24** [comment]
Hi, the url dropdown used to have it but when backdrop filter got reworked it broke so it was disabled.

Context menus can't use backdrop filter due to the way they are displayed with one exception being the context menus used in some about: pages. There is nothing I can do about it.
![image](https://user-images.githubusercontent.com/9023392/206889570-80eb5642-3ae2-41f9-99ed-a4cd053bd820.png)
![image](https://user-images.githubusercontent.com/9023392/206889574-ef51453e-4759-4582-b656-893c7583596d.png)
