### ISSUE TITLE
Broken in FF 112/113

### ISSUE THREAD

**Issue by dr-baba** [Guerra24/Firefox-UWP-Style#78]
Seems like the theme is broken in FF v113 on beta release.

Transparency effects (mica) no longer is working. Blue tab indicator/close buttons etc not showing either.

![image](https://user-images.githubusercontent.com/50979846/233899378-6498d626-1de3-4a17-be26-20427f8653d0.png)

**Comment by Guerra24** [comment]
Hi, it seems like dcomp is finally heading to the stable channel, and its fallback is broken which means Mica will be partially working in other windows like about, history, downloads... Enabling back `gfx.webrender.dcomp-win.enabled` should partially fix the issue or at least get it to a usable state.

EDIT: dcomp is already on the stable channel... but disabling it doesn't break like in beta or nightly so that change is still valid at least for 112.

**Comment by dr-baba** [comment]
Hi enabling `gfx.webrender.dcomp-win.enabled` seems to have fixed the issues for now on v113. Thanks

**Comment by Guerra24** [comment]
Closing, since the CSS properties used to get Mica working were removed from Firefox. It will work until 117 releases.

**Comment by ShayBox** [comment]
Using Firefox Nightly 121.0b9, I can see the Mica working at startup until the page loads. Since this is a CSS issue, could an extension or other modification to the browser be used to re-enable this functionality? Maybe tweaks could be made to Librewolf or another fork.

**Comment by Guerra24** [comment]
Hello @ShayBox!

[Bug 1850979](https://bugzilla.mozilla.org/show_bug.cgi?id=1850979) discusses a bit about support for transparent backdrops on Windows and contains a POC with support for mica.

If you get that working you only need to partially revert commit dd97d62f1e7fa54aba0c1c04e23427921658da5e only restoring the transparent background rules and keeping all other changes since both appearance rules and media queries changes must remain.

**Comment by ShayBox** [comment]
I'm hopeful support gets added, but I think I'm going to use Firefox ESR which still supports transparency until either FF, LF, or another fork reverts/supports transparency in the future. :+1:
