### ISSUE TITLE
Windows 10/11 Theme (question)

### ISSUE THREAD

**Issue by geextahslex** [Guerra24/Firefox-UWP-Style#86]
Hi, this is maybe a weird question but have you thought about making a fitting mssstyles Windows theme. So you can have windows and firefox look the same way?

Thank you

**Comment by Guerra24** [comment]
Hello!

This might already be a thing, so I don't think getting into the whole MSStyle thing is worth, also I believe the way Win32 renders its UI is not really fitted for this kind of style due to the use of transparency in all elements. Also, I don't think you can get it to look just right because you can't change the size of elements, Win32 UI is not really responsive by itself which makes this really hard without breaking everything.

**Comment by geextahslex** [comment]
True story, the Windows design in pretty messy

**Comment by IdkWhatToCallMe123** [comment]
There is a project that kinda does [this](https://github.com/Rectify11/Installer)
